version: '3.8'
services:
  plpbenchmarkresults:
    image: ohdsi/plpbenchmarkresults:1.0.2
    build:
      context: .
      args:
        APP_NAME: PlpBenchmarkResults
    ports:
      - "3838:3838"
    volumes:
      - ~/data/PlpBenchmarkResults/databaseFile.sqlite:/data/PlpBenchmarkResults/databaseFile.sqlite
