version: '3.8'
services:
  plpbenchmarkresults:
    image: mi-erasmus/plpbenchmarkresults:1.0.0
    build:
      context: .
      args:
        APP_NAME: PlpBenchmarkResults
    ports:
      - "3838:3838"
    volumes:
      - /Users/solonioannou/Documents/Github/mi-erasmusmc/PlpBenchmarkResults/data/sqlite/databaseFile.sqlite
